#!/usr/bin/env bash
#
# Bumps package version
#

set -eu

if [ $# -ne 1 ]; then
    echo "Usage: $0 level" >&2
    exit 1
fi

command -v cargo-release > /dev/null || cargo install cargo-release
cargo release --no-dev-version --no-publish --execute "$@"
