#!/usr/bin/env bash
#
# Checks code with clippy linter
#

set -eu

get_lint_args() {
    local action="$1"
    local lints="$2"

    sed -r '
    s/\s*#.*//
    /^\s*$/d
    s/^\s*(.*)/'"$action"' clippy::\1/
    ' <<< "$lints"
}

# A workaround to force recheck
touch src/lib.rs

for target in bins tests; do
    cargo clippy "--$target" --all-features -- -Dwarnings $(get_lint_args -A '
        collapsible_if
        new_ret_no_self
        new_without_default
        redundant_field_names
        too_many_arguments
        unit_arg

        comparison_chain
        redundant-clone
    ')
    # FIXME: ^
done
