#!/usr/bin/env bash
#
# Checks code with clippy linter
#

set -eu

get_lint_args() {
    local action="$1"
    local lints="$2"

    sed -r '
    s/\s*#.*//
    /^\s*$/d
    s/^\s*(.*)/'"$action"' clippy::\1/
    ' <<< "$lints"
}

cargo clippy --all-targets --all-features -- $(get_lint_args -A '
    collapsible_if
    needless_pass_by_value
    new_ret_no_self
    redundant_field_names
    too_many_arguments
    unit_arg
')