#!/usr/bin/env bash
#
# Run all checks and tests
#

set -eu

echo "Running clippy checks..."
./check

echo -e "\nRunning tests..."
cargo test

echo -e "\nRunning regression tests..."
./tests/run

echo -e "\nChecking that it works in real life..."
cargo run -- analyse > /dev/null

echo -e "\nAll is OK."