#!/usr/bin/env bash
#
# Run all checks and tests
#

set -eu

echo "Running clippy checks..."
# XXX(konishchev): Enable
# ./check

echo -e "\nRunning tests..."
cargo test

echo -e "\nRunning regression tests..."
./tests/run