#!/usr/bin/env bash
#
# Upgrades all subpackages' dependencies to the latest versions
#

set -eu

command -v cargo-upgrade > /dev/null || cargo install cargo-edit

for package in formatting/static_table_derive xls/xls_table_derive; do
    (
        cd "src/$package"
        cargo upgrade
        cargo update
    )
done