#!/usr/bin/env bash
#
# Upgrades all subpackages' dependencies to the latest versions
#

set -eu

command -v cargo-upgrade > /dev/null || cargo install cargo-edit

for package in formats/xls/xls_table_derive formatting/static_table_derive; do
    (
        cd "src/$package"
        cargo upgrade --pinned allow --incompatible allow
        cargo update
        cargo clean
    )
done