#!/usr/bin/env bash
#
# Upgrades all dependencies to the latest versions
#

set -eux

command -v cargo-upgrade > /dev/null || cargo install cargo-edit
cargo upgrade --pinned

# The version spec must be in sync with https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml
sed -ri '/^libsqlite3-sys =/ s/version\s*=\s*"[^"]+"/version = ">=0.8.0, <0.23.0"/' Cargo.toml

cargo update
cargo clean