#!/usr/bin/env bash
#
# Runs investments on regression tests data
#

set -eu

config="testdata/configs/$1"; shift

INVESTMENTS_NOW=$(< testdata/time)
export INVESTMENTS_NOW

"$INVESTMENTS_BINARY" --config "$config" "$@" 2>&1