#!/usr/bin/env bash
#
# Runs regression tests
#

set -eu
shopt -s nullglob

project_path="$PWD"
expected_dir="$project_path/testdata/rt_expected"
actual_dir="$project_path/testdata/rt_actual"

show-diff() {
    echo && git diff --no-index "$@"
}

export INVESTMENTS_BINARY=target/debug/investments
export INVESTMENTS_CACHE_ONLY_MODE=1

rm -f "$INVESTMENTS_BINARY" && cargo build
rm -f "$actual_dir"/*

which -s retest || cargo install --path ./tests/retest
if retest -v -v tests/rt.rt; then
    exit 0
fi

show-diff "$expected_dir" "$actual_dir"
exit 1