#!/usr/bin/env bash
#
# Updates regression tests input data
#

set -eu

wait-api-rate-limits() {
    local time="${1:-60}"
    echo "Sleeping ${time}s to fit into API rate limits..."
    sleep "$time"
}

investments() {
    local config="testdata/configs/$1"; shift
    echo "$@"
    cargo run --quiet -- --config "$config" "$@" > /dev/null
}

rate-limited-investments() {
    wait-api-rate-limits 1
    investments "$@"
}

(cd testdata && ./update)

INVESTMENTS_NOW=$(< testdata/time)
export INVESTMENTS_NOW

for portfolio in bcs bcs-iia firstrade ib investpalata kate kate-iia sber sber-iia tbank tbank-iia vtb; do
    case "$portfolio" in
        firstrade|ib) cash=10000;;
        *) cash=100000;;
    esac

    investments main sync "$portfolio"
    investments main cash "$portfolio" "$cash"

    rate-limited-investments main analyse "$portfolio"
done

for portfolio in \
    ib-complex ib-external-exchanges ib-liquidation ib-stock-split ib-reverse-stock-split \
    ib-reverse-stock-split-reverse-order ib-simple-with-lse ib-symbol-with-space ib-tax-remapping \
    ib-stock-yield-enhancement-program-not-received-yet tbank-complex; do
    investments other tax-statement "$portfolio"
done

wait-api-rate-limits
rate-limited-investments other analyse tbank-delisting
rate-limited-investments other simulate-sell open-iia-a
rate-limited-investments other simulate-sell ib-complex 1 VTRS
rate-limited-investments other simulate-sell ib-stock-split all AAPL
rate-limited-investments other simulate-sell ib-external-exchanges all IBKR
rate-limited-investments other simulate-sell ib-reverse-stock-split all AAPL all VISL
rate-limited-investments other simulate-sell tbank-mixed-currency-trade all EQMX all RSHA