#!/usr/bin/env bash
#
# Updates regression tests input data
#

set -eu

(cd testdata && ./update)

./regression_tests/investments sync ib
./regression_tests/investments cash ib 10000

./regression_tests/investments sync open
./regression_tests/investments cash open 100000