#!/usr/bin/env bash
#
# Updates regression tests input data
#

set -eu

wait-api-rate-limits() {
    sleep 1
}

(cd testdata && ./update)

for broker in bcs firstrade ib iia kate kate-iia tinkoff; do
    case "$broker" in
        firstrade|ib) cash=10000;;
        *) cash=100000;;
    esac

    ./regression_tests/investments testdata/config sync "$broker"
    ./regression_tests/investments testdata/config cash "$broker" "$cash"
    ./regression_tests/investments testdata/config analyse "$broker" > /dev/null && wait-api-rate-limits
done

./regression_tests/investments testdata/third-party-config tax-statement margin-rub > /dev/null
./regression_tests/investments testdata/third-party-config tax-statement stock-split > /dev/null