#!/usr/bin/env bash
#
# Updates regression tests input data
#

set -eu

wait-api-rate-limits() {
    sleep 1
}

(cd testdata && ./update)

for broker in bcs ib open tinkoff; do
    ./regression_tests/investments testdata/config sync "$broker"
    ./regression_tests/investments testdata/config analyse "$broker" > /dev/null && wait-api-rate-limits
done

./regression_tests/investments testdata/config cash bcs 100000
./regression_tests/investments testdata/config cash ib 10000
./regression_tests/investments testdata/config cash open 100000
./regression_tests/investments testdata/config cash tinkoff 100000

./regression_tests/investments testdata/third-party-config tax-statement margin-rub > /dev/null