name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    name: Test
    uses: KonishchevDmitry/investments/.github/workflows/test.yml@master

  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # See https://bit.ly/github-runners for actual runners

          - name: Linux
            os: ubuntu-latest
            binary_name: investments
            archive_ext: tar.bz2

          - name: Intel MacOS
            os: macos-13
            binary_name: investments
            archive_ext: tar.bz2

          - name: ARM MacOS
            os: macos-14
            binary_name: investments
            archive_ext: tar.bz2

          - name: Windows
            os: windows-latest
            binary_name: investments.exe
            archive_ext: zip

    steps:
    - uses: actions/checkout@v4

    - name: Configure build target
      run: .github/configure-build-target

    - name: Build
      env:
        CARGO_TERM_COLOR: always
        INVESTMENTS_PRECOMPILED_BINARY: yes
      run: cargo build --release --locked

    - name: Check the binary
      run: .github/check-binary release

    - name: Create archive
      id: archive
      shell: bash # Required for Windows
      run: |
        set -eux

        binary_name="${{ matrix.binary_name }}"
        mv "target/${CARGO_BUILD_TARGET:-}/release/$binary_name" .
        [[ "$(uname)" = MINGW* ]] || sudo chown 0:0 "$binary_name"

        archive_name="investments-${{ runner.os }}-${{ github.ref_name }}-${{ runner.arch }}.${{ matrix.archive_ext }}"
        archive_name="$(tr '[:upper:]' '[:lower:]' <<< "$archive_name")"
        echo "name=$archive_name" >> "$GITHUB_OUTPUT"

        case "$archive_name" in
          *.tar.bz2) tar -cjf "$archive_name" "$binary_name";;
          *.zip) 7z a "$archive_name" "$binary_name";;
          *) echo "Unexpected archive name: $archive_name." >&2; exit 1;;
        esac

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: ${{ steps.archive.outputs.name }}
        if-no-files-found: error
        compression-level: 0
        retention-days: 1

  publish:
    name: Publish

    needs: [test, build]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: "*"
        merge-multiple: true

    - name: Create release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: artifacts/*
        file_glob: true