name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 19 * * 5'
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ format('{0}-latest', matrix.os) }}

    strategy:
      matrix:
        os: [ubuntu, macos, windows]

    steps:
    - uses: actions/checkout@v4

    - name: Configure build target
      run: .github/configure-build-target

    - name: Drop caches
      run: rm Cargo.lock

    - name: Build
      run: cargo build

    - name: Check the binary
      run: .github/check-binary debug

    - name: Test
      run: cargo test --
        --skip broker_statement::bcs::tests::parse_real
        --skip broker_statement::firstrade::tests::parse_real
        --skip broker_statement::ib::confirmation::tests::parse_real
        --skip broker_statement::ib::tests::parse_real
        --skip broker_statement::open::tests::parse_real
        --skip broker_statement::tinkoff::tests::parse_real
        --skip broker_statement::tinkoff::foreign_income::tests::parse_real
        --skip tax_statement::statement::parser::tests::parse_real
        --skip telemetry::tests::telemetry